### ISSUE TITLE
One Click Reblog Not Working

### ISSUE THREAD

**Issue by rhirps** [hobinjk/XKit#76] opened 2015-07-31 20:13 UTC
I hover over the reblog button and the screen pops up but when I click the reblog button there all I get is a continuous loading symbol. It won't reblog anything.

**Comment by NursePhantump** [comment] 2015-07-31 22:12
Have you uninstalled the old x-kit? If not be sure to do so and that should fix the problem!

**Comment by eggkin** [comment] 2015-07-31 23:04
I'm having this problem too, but I've already uninstalled the old xkit and that didn't fix it. I even restarted my entire browser.
Windows 10, chrome.

**Comment by Zarggg** [comment] 2015-07-31 23:27
I've also noticed this, but I'm not yet sure what causes it.
Windows 10, Firefox. It also happened under Windows 7, so I think the OS is not a contributing factor.

**Comment by meiloslyther** [comment] 2015-08-01 05:38
Having the same problem, even after uninstalling the old xkit. Windows 7, Chrome.

**Comment by dlmarquis** [comment] 2015-08-01 06:16
Could be a cache problem. Have you tried clearing the cache?

**Comment by eggkin** [comment] 2015-08-01 06:36
Just tried that, restarted browser too, didn't work :/
Maybe it's a windows 10 thing for me? I don't quite know how this stuff works, and I only discovered the new xkit the day after I updated so I dont have any previous knowledge on how it was working.

**Comment by rhirps** [comment] 2015-08-01 14:09
I have uninstalled the old xkit. Windows 8.1, Chrome. I cleared the chache and it still didn't work. /:

**Comment by ceksie** [comment] 2015-08-01 18:05
i'm on a mac and using chrome and it doesnt work for me either

**Comment by nightpool** [comment] 2015-08-01 18:14
can you guys post your xkit and one-click-postage versions?
![image](https://cloud.githubusercontent.com/assets/233815/9022978/2935a1b4-384f-11e5-9521-2c7db5884309.png)
![image](https://cloud.githubusercontent.com/assets/233815/9022980/2e4c2eca-384f-11e5-83ca-f668cb9ac080.png)

**Comment by nightpool** [comment] 2015-08-01 18:15
Also, a list of the extensions you have installed would be helpful.

**Comment by rhirps** [comment] 2015-08-01 18:28
![screenshot 15](https://cloud.githubusercontent.com/assets/13593068/9023024/06b02ba0-3859-11e5-8572-c7bfe1f3a867.png)
![screenshot 16](https://cloud.githubusercontent.com/assets/13593068/9023025/06b5cf92-3859-11e5-883c-48d045763188.png)
xinbox, one click postage, one click reply, tweaks, go to das, activity+, anti-capitalism, auto load images, audio downloader, auto tagger, blacklist, classic search, convert links, drafts+, enhanced queue, mass+, mass deleter, no recommended, notification block, notifications+, outbox, post block, quick tags, read more now, reblog as text, reply viewer, reblog yourself, search likes, tag replacer, timestamps, open in tabs, editable reblogs

**Comment by eggkin** [comment] 2015-08-01 18:30
Xkit: 7.6.5
One-click postage: 4.0.0
extensions: all the default ones, timestamps, xcloud, tags on sidebar, classic search, reblog yourself, read more now, reblog as text, outbox, drafts+, convert links, blacklist, color quotes, search likes, servant, auto load images, tag replacer, find inactive, separator, view my tags, audio+, notifications+, access kit, open in tabs, mass+, activity+, Xwidgets, profiler, mass deleter, user menus, xstats, view on dash, tagviewer, autotagger, quick tags, enhanced queue, post block, jk across pages, notification block, post archiver, limit people, reply viewer, retags, no recommended, no sidebar, soft refresh, show originals, anti-capitalism, editable reblogs, header options, lethe

some of those I have disabled, however, but those are all the ones installed
(disabled: tags on sidebar, classic search, separator, access kit, activity+, view on dash, quick tags, jk across pages, limit people, soft refresh, show originals, header options, lethe)

**Comment by meiloslyther** [comment] 2015-08-01 18:51
xkit: 7.6.5
One-click postage: 4.0.0
extensions: xinbox, one-click postage, one-click reply, tweaks, go-to-dash, anti-capitalism, blacklist, audio downloader, auto load images, auto tagger, color quotes, convert links, enhanced queue, no recommended, no sidebar, open in tabs, outbox, profiler, user menus+, quick tags, read more now, reblog as text, reply viewer, retags, tag viewer, timestamps, view on dash, estufar's sidebar fix

**Comment by nightpool** [comment] 2015-08-01 19:02
okay these are the extensions you guys all share:

    'anti-capitalism', 'auto tagger', 'blacklist', 'convert links', 'editable reblogs', 'enhanced queue', 'no recommended', 'one click postage', 'open in tabs', 'outbox', 'read more now', 'reblog as text', 'reply viewer'

I'll take a look and see if I can reproduce this.

**Comment by ceksie** [comment] 2015-08-01 19:08
http://i.gyazo.com/74f8c7cd18ec4efcabb3743b6dd3f087.png
http://i.gyazo.com/85ecd6b65f9f51899c05955140e9dff4.png
http://i.gyazo.com/016eff5d3e4c5b33b8cb850ebd8a3e98.png

**Comment by nightpool** [comment] 2015-08-01 20:05
Okay so just to confirm: for all of you guys, the extension won't stop loading?

**Comment by ceksie** [comment] 2015-08-01 20:06
nope

**Comment by ceksie** [comment] 2015-08-01 20:07
at least not as long as i've waited?

**Comment by rhirps** [comment] 2015-08-01 20:08
Yes, it won't stop loading.

**Comment by eggkin** [comment] 2015-08-01 20:23
like, I get the menu to pop up, hit reblog, and the loading symbol doesnt go away, so yeah.

**Comment by rhirps** [comment] 2015-08-01 20:24
Yeah same as eggkin but it doesn't reblog the post at all.

**Comment by eggkin** [comment] 2015-08-01 20:25
Yeah, rhirps, that's what I mean, it doesn't reblog, it is eternally trying to process the request.

**Comment by hobinjk** [comment] 2015-08-01 20:28
"Not loading" is usually the result of an error being encountered in the API call that sends the post. This may be due to a change in protocol accompanying the Tumblr update

**Comment by rhirps** [comment] 2015-08-01 20:30
This problem has been going on since before the update with me.

**Comment by meiloslyther** [comment] 2015-08-01 20:40
I'm not sure what update you mean, hobinjk, but this has been going on for at least a week for me, maybe two.

**Comment by nightpool** [comment] 2015-08-01 20:42
okay I still can't reproduce this, but here's a modified version of one_click_postage that should give us more information about what problem's you're running into:

https://gist.githubusercontent.com/nightpool/aa763df7f1b700e837fd/raw/56b5d9c8196145d06c3ff2747cd84a953d09832b/one_click_postage.js

- open the document, press ctrl-a and then copy
- open up [tumblr.com/xkit_editor](//tumblr.com/xkit_editor)
- open extension -> one click postage
- ctrl-a, paste
- open a new tumblr dashboard, try to reblog a post
- an error window should pop up. Copy and paste the error you get.

unfortunately this is kludgy, but its the only way we have of figuring out what's going on now.

**Comment by ceksie** [comment] 2015-08-01 20:44
for me it's still loading like it was before

**Comment by nightpool** [comment] 2015-08-01 20:45
@hobinjk i dunno, the onerror handlers for those calls are pretty well populated. there aren't many places that aren't covered by a try/catch block.

**Comment by nightpool** [comment] 2015-08-01 20:47
@ceksie if you open up the developer console, (cmd-alt-j) do you see any red errors?

**Comment by ceksie** [comment] 2015-08-01 20:48
yes lots i'll get a pic

**Comment by ceksie** [comment] 2015-08-01 20:48
http://gyazo.com/0c9483e0d9cf748f2c92ad86d69f0636

**Comment by eggkin** [comment] 2015-08-01 20:51
The edit didn't work for me, I am still getting the same problem.

**Comment by nightpool** [comment] 2015-08-01 21:03
Found it! this is a problem with autotagger, but only if you've enabled "replace dashes in the username with spaces"

disable this option for now, and then we'll have a fix out soon that will allow you to re-enable it.

**Comment by ceksie** [comment] 2015-08-01 21:05
works now, thanks!

**Comment by eggkin** [comment] 2015-08-01 21:07
Works wonderfully now, with that disabled, thanks!

**Comment by nightpool** [comment] 2015-08-01 21:21
@hobinjk do we have a translation layer between the returned 'svc/post' models and xkit.interfaces.post objects? it looks like the code assumes they're going to be the same thing. (which is bad for us if tumblr changes any of their API)

**Comment by hobinjk** [comment] 2015-08-01 21:27
@nightpool No, if I remember correctly the XKit.interface.post objects are only generated by scraping the ".post" elements whereas svc/post/* can do whatever it wants to. It would definitely be worthwhile to create XKit.interface.post.delete, XKit.interface.post.update, and XKit.interface.post.fetch. The main reason that hasn't already happened is that the object that the svc/post/* methods use is really poorly documented and changes significantly based on what it represents.

**Comment by hobinjk** [comment] 2015-08-04 06:12
Closing because this hopefully works now.

**Closed by hobinjk** 2015-08-04 06:12 UTC
